name: pytorch-nvidia
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - icu=73.2
  - idna=3.6
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.11.6
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.2.1
  - numpy=1.26.3
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.0
  - pillow=9.4.0
  - pip=23.3.2
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.10.13
  - python_abi=3.10
  - pytorch=2.1.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=69.0.3
  - sympy=1.12
  - tbb=2021.11.0
  - tk=8.6.13
  - torchaudio=2.1.1
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.1.0
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - antlr4-python3-runtime==4.9.3
      - black==23.12.1
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.0.7
      - fonttools==4.47.0
      - fvcore==0.1.5.post20221221
      - hydra-core==1.3.2
      - iopath==0.1.9
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - mypy-extensions==1.0.0
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - pathspec==0.12.1
      - platformdirs==4.1.0
      - portalocker==2.8.2
      - pycocotools==2.0.7
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - six==1.16.0
      - tabulate==0.9.0
      - tomli==2.0.1
      - tqdm==4.66.1
      - yacs==0.1.8
